apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: 968225077300.dkr.ecr.us-east-1.amazonaws.com/strimzi/producer:latest
        name: producer
