apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: producer
  name: producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: producer
    spec:
      containers:
      - image: 968225077300.dkr.ecr.us-east-1.amazonaws.com/strimzi/producer
        name: producer
        resources: {}
status: {}
